# agent/reporter.py

import datetime
import json
from jinja2 import Template

class Reporter:
    """
    Generates JSON + HTML reports with:
    - Logs
    - Screenshots
    - Video link
    - Error type detection
    """

    def detect_error_category(self, logs):
        for line in logs:
            if "Timeout" in line:
                return "Timeout Error"
            if "not found" in line:
                return "Element Not Found"
            if "AssertionError" in line:
                return "Assertion Failure"
        return "Unknown Error"

    def generate_pdf_report(self, report_data, uid):
        from fpdf import FPDF
        import os

        # Ensure output directory exists even if called standalone
        os.makedirs("tests", exist_ok=True)

        pdf = FPDF()
        pdf.add_page()

        # --- HEADER ---
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(30, 41, 59)  # Slate 800
        pdf.cell(0, 15, "AI WEB TESTING AGENT", ln=True, align="C")
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 5, "TESTING SUMMARY REPORT", ln=True, align="C")
        pdf.ln(10)

        # --- SUMMARY BOX ---
        pdf.set_fill_color(248, 250, 252)
        pdf.rect(10, 40, 190, 40, "F")
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_xy(15, 45)
        pdf.cell(40, 10, "Test ID:")
        pdf.set_font("Helvetica", "", 12)
        pdf.cell(0, 10, uid, ln=True)

        pdf.set_font("Helvetica", "B", 12)
        pdf.set_x(15)
        pdf.cell(40, 10, "Date & Time:")
        pdf.set_font("Helvetica", "", 12)
        pdf.cell(0, 10, report_data["timestamp"], ln=True)

        status_text = "SUCCESS" if report_data["success"] else "ISSUE FOUND"
        status_color = (16, 185, 129) if report_data["success"] else (239, 68, 68)

        pdf.set_font("Helvetica", "B", 12)
        pdf.set_x(15)
        pdf.cell(40, 10, "Outcome:")
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(*status_color)
        pdf.cell(0, 10, status_text, ln=True)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(10)

        # --- LOGS ---
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Step Details", ln=True)
        pdf.set_font("Courier", "", 9)
        pdf.set_fill_color(241, 245, 249)

        for log in report_data["logs"]:
            clean_log = log.encode('latin-1', 'replace').decode('latin-1')
            pdf.multi_cell(0, 5, f"> {clean_log}", border=0, fill=True)
            pdf.ln(1)

        pdf.ln(10)

        # --- SCREENSHOTS ---
        if report_data.get("screenshots"):
            pdf.set_font("Helvetica", "B", 14)
            pdf.cell(0, 10, "Screenshots", ln=True)
            for sc in report_data["screenshots"]:
                if os.path.exists(sc):
                    try:
                        pdf.image(sc, w=170)
                        pdf.ln(5)
                    except Exception as img_err:
                        pdf.set_font("Helvetica", "I", 10)
                        pdf.cell(0, 10, f"[Image load error: {sc} — {img_err}]", ln=True)

        # --- FOOTER ---
        pdf.set_y(-20)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(148, 163, 184)
        pdf.cell(0, 10, "Generated by AI Web Testing Agent", align="C")

        pdf_path = f"tests/report_{uid}.pdf"
        pdf.output(pdf_path)
        return pdf_path

    def generate_report(self, exec_result, test_id=None):
        import uuid
        import os

        uid = test_id or str(uuid.uuid4())[:8]

        # Guard against None or malformed exec_result
        if not exec_result or not isinstance(exec_result, dict):
            exec_result = {"success": False, "logs": ["exec_result was None or invalid"], "screenshots": []}

        # Ensure required keys exist
        exec_result.setdefault("success", False)
        exec_result.setdefault("logs", [])
        exec_result.setdefault("screenshots", [])

        report = {
            "timestamp": str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")),
            "success": exec_result["success"],
            "logs": exec_result["logs"],
            "screenshots": exec_result.get("screenshots", []),
        }

        json_report_path = f"tests/report_{uid}.json"
        html_report_path = f"tests/report_{uid}.html"

        os.makedirs("tests", exist_ok=True)

        with open(json_report_path, "wb") as f:
            f.write(json.dumps(report, indent=4).encode("utf-8", errors="replace"))

        # Render HTML report
        html_template = """
        <html>
        <head>
            <title>Test Result - {{ uid }}</title>
            <style>
                body { font-family: sans-serif; margin: 10px; background: #f4f4f9; }
                .card { background: white; padding: 15px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
                .success { color: green; font-weight: bold; }
                .failure { color: red; font-weight: bold; }
                img { max-width: 600px; border: 1px solid #ccc; margin-top: 10px; display: block; }
                pre { background: #eee; padding: 10px; border-radius: 4px; overflow-x: auto; }
            </style>
        </head>
        <body>
            <div class="card">
                <h1>Test Result Summary</h1>
                <p><b>Test ID:</b> {{ uid }}</p>
                <p><b>Time:</b> {{ timestamp }}</p>
                <p><b>Outcome:</b> <span class="{{ 'success' if success else 'failure' }}">{{ 'SUCCESS' if success else 'ISSUE FOUND' }}</span></p>

                <h2>Step Details</h2>
                <pre>{% for log in logs %}{{ log }}\n{% endfor %}</pre>

                {% if screenshots %}
                <h2>Screenshots</h2>
                {% for sc in screenshots %}
                <img src="../{{ sc }}" alt="Screenshot">
                {% endfor %}
                {% endif %}
            </div>
        </body>
        </html>
        """

        html = Template(html_template).render(
            uid=uid,
            timestamp=report["timestamp"],
            success=report["success"],
            logs=report["logs"],
            screenshots=report["screenshots"]
        )

        try:
            with open(html_report_path, "wb") as f:
                f.write(html.encode("utf-8", errors="replace"))
        except Exception as html_err:
            print(f"HTML Report Write Failed: {html_err}")

        try:
            pdf_path = self.generate_pdf_report(report, uid)
        except Exception as e:
            print(f"PDF Generation Failed: {e}")
            pdf_path = None

        return html_report_path, json_report_path, pdf_path